version: "3"
services:
    frontend:
        container_name: carimus-app
        build:
            context: ./carimus-app
            dockerfile: Dockerfile
        image: lascenzi/carimus-app
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
    backend:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: lascenzi/server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/app