version: "3"
services:
    frontend:
        container_name: carimus-app
        build:
            context: ./carimus-app
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on: 
        - backend

    backend:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        depends_on: 
        - database
    database:
        container_name: database
        build:
            context: ./database
            dockerfile: Dockerfile
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=carimus_db
